--
-- PostgreSQL database dump
--

\restrict GvZjcuux9dxt7n4uc9x1c1CSndxDb3dixbp84gOzF82NAgSnJrf6eRhEv3f3cfk

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-06-28 18:11:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 24761)
-- Name: charity; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA charity;


ALTER SCHEMA charity OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 24814)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE charity."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24813)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: charity; Owner: postgres
--

ALTER TABLE charity."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME charity."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24762)
-- Name: AspNetRoles; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE charity."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24829)
-- Name: AspNetUserClaims; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE charity."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24828)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: charity; Owner: postgres
--

ALTER TABLE charity."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME charity."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 24843)
-- Name: AspNetUserLogins; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE charity."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24858)
-- Name: AspNetUserRoles; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE charity."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24877)
-- Name: AspNetUserTokens; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE charity."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24770)
-- Name: AuditLogs; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."AuditLogs" (
    "Id" uuid NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "UserId" text,
    "Action" character varying(100) NOT NULL,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" text,
    "OldValues" text,
    "NewValues" text,
    "IpAddress" character varying(50),
    "UserAgent" text,
    "CorrelationId" uuid
);


ALTER TABLE charity."AuditLogs" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24892)
-- Name: Beneficiaries; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."Beneficiaries" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "NationalId" character varying(20) NOT NULL,
    "DateOfBirth" date NOT NULL,
    "Gender" integer NOT NULL,
    "AddressAr" character varying(500),
    "AddressEn" text,
    "City" character varying(100),
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."Beneficiaries" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 25038)
-- Name: Consultations; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."Consultations" (
    "Id" uuid NOT NULL,
    "RequestId" uuid NOT NULL,
    "QRCodeTokenId" uuid NOT NULL,
    "DoctorId" text NOT NULL,
    "DiagnosisAr" character varying(2000) NOT NULL,
    "DiagnosisEn" character varying(2000) NOT NULL,
    "NotesAr" character varying(4000),
    "NotesEn" text,
    "RecommendationsAr" character varying(2000),
    "RecommendationsEn" text,
    "ConsultedAt" timestamp with time zone NOT NULL,
    "DoctorId1" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."Consultations" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24911)
-- Name: Doctors; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."Doctors" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "SpecialtyId" uuid NOT NULL,
    "LicenseNumber" character varying(50) NOT NULL,
    "ClinicAddress" character varying(500),
    "ClinicPhone" character varying(20),
    "MaxDailySlots" integer NOT NULL,
    "IsAvailable" boolean NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."Doctors" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 24936)
-- Name: LoginHistories; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."LoginHistories" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "LoginAt" timestamp with time zone NOT NULL,
    "IpAddress" text,
    "UserAgent" text,
    "LoginMethod" integer NOT NULL,
    "Success" boolean NOT NULL,
    "FailureReason" text
);


ALTER TABLE charity."LoginHistories" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 24975)
-- Name: MedicalRequests; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."MedicalRequests" (
    "Id" uuid NOT NULL,
    "BeneficiaryId" uuid NOT NULL,
    "SpecialtyId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "DescriptionAr" character varying(2000),
    "DescriptionEn" text,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "ReviewedBy" text,
    "ReviewedAt" timestamp with time zone,
    "ReviewNoteAr" character varying(1000),
    "ReviewNoteEn" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."MedicalRequests" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 24953)
-- Name: OtpRecords; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."OtpRecords" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "CodeHash" character varying(256) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "FailedAttempts" integer NOT NULL,
    "IsLocked" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."OtpRecords" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 24999)
-- Name: QRCodeTokens; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."QRCodeTokens" (
    "Id" uuid NOT NULL,
    "RequestId" uuid NOT NULL,
    "TokenHash" character varying(256) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "UsedAt" timestamp with time zone,
    "UsedByDoctorId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."QRCodeTokens" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 25018)
-- Name: RequestDocuments; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."RequestDocuments" (
    "Id" uuid NOT NULL,
    "RequestId" uuid NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "DocumentType" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."RequestDocuments" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24781)
-- Name: Specialties; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."Specialties" (
    "Id" uuid NOT NULL,
    "NameAr" character varying(200) NOT NULL,
    "NameEn" character varying(200) NOT NULL,
    "DescriptionAr" text,
    "DescriptionEn" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text
);


ALTER TABLE charity."Specialties" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24794)
-- Name: Users; Type: TABLE; Schema: charity; Owner: postgres
--

CREATE TABLE charity."Users" (
    "Id" text NOT NULL,
    "FullNameAr" text NOT NULL,
    "FullNameEn" text NOT NULL,
    "UserType" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "PreferredLanguage" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE charity."Users" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24754)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 5115 (class 0 OID 24814)
-- Dependencies: 226
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 5110 (class 0 OID 24762)
-- Dependencies: 221
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
049bd2ed-d7c2-4c2e-977b-947a857e8ac5	Administrator	ADMINISTRATOR	b473e498-bb0f-405f-86f7-c625d555012a
bdb23df8-88c3-489b-906b-b53bbda0b35b	Staff	STAFF	9c0189ac-3514-437d-8d5a-298861758fdb
7fbb01b1-81e7-410c-b167-db8b154692d2	Doctor	DOCTOR	6860583b-c0f4-41e1-8fb4-04b1793bde1d
6b09a22a-5903-4489-9e67-24897a4420ef	Beneficiary	BENEFICIARY	5025204b-e252-4cab-9191-da5a895f17d5
\.


--
-- TOC entry 5117 (class 0 OID 24829)
-- Dependencies: 228
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 5118 (class 0 OID 24843)
-- Dependencies: 229
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- TOC entry 5119 (class 0 OID 24858)
-- Dependencies: 230
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
b0655c1e-80c3-4aaf-b83e-afbdeb835bc2	049bd2ed-d7c2-4c2e-977b-947a857e8ac5
85257c3e-52ab-4155-bf00-b306b6383a21	6b09a22a-5903-4489-9e67-24897a4420ef
\.


--
-- TOC entry 5120 (class 0 OID 24877)
-- Dependencies: 231
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- TOC entry 5111 (class 0 OID 24770)
-- Dependencies: 222
-- Data for Name: AuditLogs; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."AuditLogs" ("Id", "Timestamp", "UserId", "Action", "EntityType", "EntityId", "OldValues", "NewValues", "IpAddress", "UserAgent", "CorrelationId") FROM stdin;
966830ec-8aab-4f7c-8133-d3cb91ec8985	2026-06-26 21:37:54.492777+04	\N	Auth.Login.Success	ApplicationUser	b0655c1e-80c3-4aaf-b83e-afbdeb835bc2	\N	{"method":"password","roles":"Administrator"}	::1	\N	15c3493b-f727-41a2-b446-d002c2d9d699
6fb18262-9f07-425c-9f32-640cffe83f57	2026-06-26 21:54:35.977585+04	\N	Auth.Login.Success	ApplicationUser	b0655c1e-80c3-4aaf-b83e-afbdeb835bc2	\N	{"method":"password","roles":"Administrator"}	::1	\N	240662a8-c6cd-400c-8b9d-cb1a7de1f879
c77301a8-1e6f-427a-8761-aa8d52308f58	2026-06-26 21:59:37.526661+04	\N	Auth.Login.Success	ApplicationUser	b0655c1e-80c3-4aaf-b83e-afbdeb835bc2	\N	{"method":"password","roles":"Administrator"}	::1	\N	b57f386b-05b6-4689-b329-389332c1d74e
3122ca26-1938-4d71-9a05-eb7d5ffd39a8	2026-06-26 22:02:11.450402+04	\N	Auth.Login.Success	ApplicationUser	b0655c1e-80c3-4aaf-b83e-afbdeb835bc2	\N	{"method":"password","roles":"Administrator"}	::1	\N	fc7c7dc8-ec69-4f75-990b-44d20999c43f
5ca243e2-9e4f-443e-8eda-420a3f2eb20e	2026-06-27 19:52:47.332652+04	\N	Auth.Login.Success	ApplicationUser	b0655c1e-80c3-4aaf-b83e-afbdeb835bc2	\N	{"method":"password"}	::1	\N	221f83fa-687d-44b0-84ae-1d6754c28ab8
e5aa1d87-bec5-44e1-8f77-b52ba5f4ea21	2026-06-27 21:31:39.464288+04	\N	Beneficiary.Registered	ApplicationUser	85257c3e-52ab-4155-bf00-b306b6383a21	\N	{"phone":"00201105047868","nationalId":"20999457345"}	::1	\N	771300b8-ee88-4b96-831e-7f296da49f94
d9edfb9f-8089-40c6-827e-2c2ad1dd4540	2026-06-27 21:32:32.534663+04	\N	Auth.Login.Success	ApplicationUser	85257c3e-52ab-4155-bf00-b306b6383a21	\N	{"method":"password"}	::1	\N	1c2450f6-4176-4627-b3b1-a8a189a78cea
c68aac8a-26b5-4c10-83de-1344403dfa5b	2026-06-27 21:46:44.312586+04	\N	Auth.Login.Success	ApplicationUser	85257c3e-52ab-4155-bf00-b306b6383a21	\N	{"method":"password"}	::1	\N	7713f7d2-0ce1-4297-8cf6-5b077b053079
43d1c518-823d-41a8-a31d-82f4bf0f8e87	2026-06-27 22:12:16.271557+04	\N	Auth.Login.Success	ApplicationUser	85257c3e-52ab-4155-bf00-b306b6383a21	\N	{"method":"password"}	::1	\N	824bc6aa-5787-455c-be2d-5cc55fb6deb0
431b0e12-d95f-4297-be24-7d22f34f85fd	2026-06-27 22:13:02.038762+04	85257c3e-52ab-4155-bf00-b306b6383a21	Auth.Logout	ApplicationUser	85257c3e-52ab-4155-bf00-b306b6383a21	\N	\N	::1	\N	1140ef43-5dd5-48ed-b319-3ee05836e652
\.


--
-- TOC entry 5121 (class 0 OID 24892)
-- Dependencies: 232
-- Data for Name: Beneficiaries; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."Beneficiaries" ("Id", "UserId", "NationalId", "DateOfBirth", "Gender", "AddressAr", "AddressEn", "City", "Notes", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
a2bcede8-4a43-44a4-b869-4a9c377ee66b	85257c3e-52ab-4155-bf00-b306b6383a21	20999457345	1994-09-28	1	اعطو	\N	بني مزر	\N	2026-06-27 21:31:39.440756+04	\N	f	\N	\N
\.


--
-- TOC entry 5128 (class 0 OID 25038)
-- Dependencies: 239
-- Data for Name: Consultations; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."Consultations" ("Id", "RequestId", "QRCodeTokenId", "DoctorId", "DiagnosisAr", "DiagnosisEn", "NotesAr", "NotesEn", "RecommendationsAr", "RecommendationsEn", "ConsultedAt", "DoctorId1", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
\.


--
-- TOC entry 5122 (class 0 OID 24911)
-- Dependencies: 233
-- Data for Name: Doctors; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."Doctors" ("Id", "UserId", "SpecialtyId", "LicenseNumber", "ClinicAddress", "ClinicPhone", "MaxDailySlots", "IsAvailable", "Notes", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
\.


--
-- TOC entry 5123 (class 0 OID 24936)
-- Dependencies: 234
-- Data for Name: LoginHistories; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."LoginHistories" ("Id", "UserId", "LoginAt", "IpAddress", "UserAgent", "LoginMethod", "Success", "FailureReason") FROM stdin;
\.


--
-- TOC entry 5125 (class 0 OID 24975)
-- Dependencies: 236
-- Data for Name: MedicalRequests; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."MedicalRequests" ("Id", "BeneficiaryId", "SpecialtyId", "Status", "DescriptionAr", "DescriptionEn", "SubmittedAt", "ReviewedBy", "ReviewedAt", "ReviewNoteAr", "ReviewNoteEn", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
\.


--
-- TOC entry 5124 (class 0 OID 24953)
-- Dependencies: 235
-- Data for Name: OtpRecords; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."OtpRecords" ("Id", "UserId", "PhoneNumber", "CodeHash", "ExpiresAt", "IsUsed", "FailedAttempts", "IsLocked", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
\.


--
-- TOC entry 5126 (class 0 OID 24999)
-- Dependencies: 237
-- Data for Name: QRCodeTokens; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."QRCodeTokens" ("Id", "RequestId", "TokenHash", "ExpiresAt", "IsUsed", "UsedAt", "UsedByDoctorId", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
\.


--
-- TOC entry 5127 (class 0 OID 25018)
-- Dependencies: 238
-- Data for Name: RequestDocuments; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."RequestDocuments" ("Id", "RequestId", "FileName", "FilePath", "FileSizeBytes", "DocumentType", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
\.


--
-- TOC entry 5112 (class 0 OID 24781)
-- Dependencies: 223
-- Data for Name: Specialties; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."Specialties" ("Id", "NameAr", "NameEn", "DescriptionAr", "DescriptionEn", "IsActive", "CreatedAt", "UpdatedAt", "IsDeleted", "CreatedBy", "UpdatedBy") FROM stdin;
52eb1728-bd4a-4865-8517-14528b6b59de	طب عام	General Medicine	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
58ad0edc-bc46-409e-9089-9925dd37374e	طب الأسنان	Dentistry	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
b08d0a24-5898-4e04-801a-f5c60684a237	طب العيون	Ophthalmology	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
5ee98808-24b4-42d3-958c-34636036cb6e	طب الأطفال	Pediatrics	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
ac01f158-0608-4498-aa99-91ec6e841348	أمراض القلب	Cardiology	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
f92f899f-c252-49fe-adc2-17d865a58483	أمراض الجهاز العصبي	Neurology	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
ffd8a327-9fdb-41a1-96db-c8febfcb5947	جراحة العظام	Orthopedics	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
41c33b79-9624-4799-a041-a827304fcd67	الجلدية	Dermatology	\N	\N	t	2026-06-27 17:28:14.356468+04	\N	f	\N	\N
\.


--
-- TOC entry 5113 (class 0 OID 24794)
-- Dependencies: 224
-- Data for Name: Users; Type: TABLE DATA; Schema: charity; Owner: postgres
--

COPY charity."Users" ("Id", "FullNameAr", "FullNameEn", "UserType", "IsActive", "CreatedAt", "UpdatedAt", "CreatedBy", "PreferredLanguage", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
b0655c1e-80c3-4aaf-b83e-afbdeb835bc2	مدير النظام	System Administrator	4	t	2026-06-26 18:12:47.122382+04	\N	\N	ar	superadmin	SUPERADMIN	admin@charityhealth.org	ADMIN@CHARITYHEALTH.ORG	t	AQAAAAIAAYagAAAAEBIbyFcgusrcq7w/U++h+l10uOqzjirA7Q7NcsHAxY+ySDhKIIxR3THCqSpOI2V3TA==	7UZZUHQR6DECEHLRBCAXAKOGS34CQ6BG	0ebe0e08-e190-4d25-a9a6-c956184fb925	+96891000001	t	f	\N	t	0
85257c3e-52ab-4155-bf00-b306b6383a21	محمد احمد عبد السميع		1	t	2026-06-27 21:31:38.883548+04	\N	\N	ar	00201105047868	00201105047868	mm0115810@gmail.com	MM0115810@GMAIL.COM	f	AQAAAAIAAYagAAAAEGpz29S5A9kSjp2AlYhbhObO2lt4XsURjYflC6YCdIaE+sxZ4xJo0sxeplpXZcDDfw==	JSG3JFEQZGINNCW27EN2ANSMUI3QWNRY	5c19b46e-f3ee-4139-87de-793140dbbc58	00201105047868	f	f	\N	t	0
\.


--
-- TOC entry 5109 (class 0 OID 24754)
-- Dependencies: 220
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260626140900_InitialCreate	10.0.9
\.


--
-- TOC entry 5134 (class 0 OID 0)
-- Dependencies: 225
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: charity; Owner: postgres
--

SELECT pg_catalog.setval('charity."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 5135 (class 0 OID 0)
-- Dependencies: 227
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: charity; Owner: postgres
--

SELECT pg_catalog.setval('charity."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 4898 (class 2606 OID 24822)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4883 (class 2606 OID 24769)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 4901 (class 2606 OID 24837)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4904 (class 2606 OID 24852)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 4907 (class 2606 OID 24866)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 4909 (class 2606 OID 24886)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 4888 (class 2606 OID 24780)
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- TOC entry 4913 (class 2606 OID 24905)
-- Name: Beneficiaries PK_Beneficiaries; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Beneficiaries"
    ADD CONSTRAINT "PK_Beneficiaries" PRIMARY KEY ("Id");


--
-- TOC entry 4943 (class 2606 OID 25054)
-- Name: Consultations PK_Consultations; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Consultations"
    ADD CONSTRAINT "PK_Consultations" PRIMARY KEY ("Id");


--
-- TOC entry 4918 (class 2606 OID 24925)
-- Name: Doctors PK_Doctors; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Doctors"
    ADD CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id");


--
-- TOC entry 4921 (class 2606 OID 24947)
-- Name: LoginHistories PK_LoginHistories; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."LoginHistories"
    ADD CONSTRAINT "PK_LoginHistories" PRIMARY KEY ("Id");


--
-- TOC entry 4930 (class 2606 OID 24988)
-- Name: MedicalRequests PK_MedicalRequests; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."MedicalRequests"
    ADD CONSTRAINT "PK_MedicalRequests" PRIMARY KEY ("Id");


--
-- TOC entry 4925 (class 2606 OID 24969)
-- Name: OtpRecords PK_OtpRecords; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."OtpRecords"
    ADD CONSTRAINT "PK_OtpRecords" PRIMARY KEY ("Id");


--
-- TOC entry 4935 (class 2606 OID 25012)
-- Name: QRCodeTokens PK_QRCodeTokens; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."QRCodeTokens"
    ADD CONSTRAINT "PK_QRCodeTokens" PRIMARY KEY ("Id");


--
-- TOC entry 4938 (class 2606 OID 25032)
-- Name: RequestDocuments PK_RequestDocuments; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."RequestDocuments"
    ADD CONSTRAINT "PK_RequestDocuments" PRIMARY KEY ("Id");


--
-- TOC entry 4891 (class 2606 OID 24793)
-- Name: Specialties PK_Specialties; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Specialties"
    ADD CONSTRAINT "PK_Specialties" PRIMARY KEY ("Id");


--
-- TOC entry 4894 (class 2606 OID 24812)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4881 (class 2606 OID 24760)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4892 (class 1259 OID 25096)
-- Name: EmailIndex; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "EmailIndex" ON charity."Users" USING btree ("NormalizedEmail");


--
-- TOC entry 4896 (class 1259 OID 25070)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON charity."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 4899 (class 1259 OID 25072)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON charity."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 4902 (class 1259 OID 25073)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON charity."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 4905 (class 1259 OID 25074)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON charity."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 4885 (class 1259 OID 25075)
-- Name: IX_AuditLogs_Timestamp; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Timestamp" ON charity."AuditLogs" USING btree ("Timestamp");


--
-- TOC entry 4886 (class 1259 OID 25076)
-- Name: IX_AuditLogs_UserId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_UserId" ON charity."AuditLogs" USING btree ("UserId");


--
-- TOC entry 4910 (class 1259 OID 25077)
-- Name: IX_Beneficiaries_NationalId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Beneficiaries_NationalId" ON charity."Beneficiaries" USING btree ("NationalId");


--
-- TOC entry 4911 (class 1259 OID 25078)
-- Name: IX_Beneficiaries_UserId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Beneficiaries_UserId" ON charity."Beneficiaries" USING btree ("UserId");


--
-- TOC entry 4939 (class 1259 OID 25079)
-- Name: IX_Consultations_DoctorId1; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_Consultations_DoctorId1" ON charity."Consultations" USING btree ("DoctorId1");


--
-- TOC entry 4940 (class 1259 OID 25080)
-- Name: IX_Consultations_QRCodeTokenId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Consultations_QRCodeTokenId" ON charity."Consultations" USING btree ("QRCodeTokenId");


--
-- TOC entry 4941 (class 1259 OID 25081)
-- Name: IX_Consultations_RequestId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Consultations_RequestId" ON charity."Consultations" USING btree ("RequestId");


--
-- TOC entry 4914 (class 1259 OID 25082)
-- Name: IX_Doctors_LicenseNumber; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Doctors_LicenseNumber" ON charity."Doctors" USING btree ("LicenseNumber");


--
-- TOC entry 4915 (class 1259 OID 25083)
-- Name: IX_Doctors_SpecialtyId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_Doctors_SpecialtyId" ON charity."Doctors" USING btree ("SpecialtyId");


--
-- TOC entry 4916 (class 1259 OID 25084)
-- Name: IX_Doctors_UserId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Doctors_UserId" ON charity."Doctors" USING btree ("UserId");


--
-- TOC entry 4919 (class 1259 OID 25085)
-- Name: IX_LoginHistories_UserId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_LoginHistories_UserId" ON charity."LoginHistories" USING btree ("UserId");


--
-- TOC entry 4926 (class 1259 OID 25086)
-- Name: IX_MedicalRequests_BeneficiaryId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_MedicalRequests_BeneficiaryId" ON charity."MedicalRequests" USING btree ("BeneficiaryId");


--
-- TOC entry 4927 (class 1259 OID 25087)
-- Name: IX_MedicalRequests_SpecialtyId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_MedicalRequests_SpecialtyId" ON charity."MedicalRequests" USING btree ("SpecialtyId");


--
-- TOC entry 4928 (class 1259 OID 25088)
-- Name: IX_MedicalRequests_Status; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_MedicalRequests_Status" ON charity."MedicalRequests" USING btree ("Status");


--
-- TOC entry 4922 (class 1259 OID 25089)
-- Name: IX_OtpRecords_PhoneNumber_IsUsed; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_OtpRecords_PhoneNumber_IsUsed" ON charity."OtpRecords" USING btree ("PhoneNumber", "IsUsed");


--
-- TOC entry 4923 (class 1259 OID 25090)
-- Name: IX_OtpRecords_UserId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_OtpRecords_UserId" ON charity."OtpRecords" USING btree ("UserId");


--
-- TOC entry 4931 (class 1259 OID 25091)
-- Name: IX_QRCodeTokens_IsUsed_ExpiresAt; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_QRCodeTokens_IsUsed_ExpiresAt" ON charity."QRCodeTokens" USING btree ("IsUsed", "ExpiresAt");


--
-- TOC entry 4932 (class 1259 OID 25092)
-- Name: IX_QRCodeTokens_RequestId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_QRCodeTokens_RequestId" ON charity."QRCodeTokens" USING btree ("RequestId");


--
-- TOC entry 4933 (class 1259 OID 25093)
-- Name: IX_QRCodeTokens_TokenHash; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_QRCodeTokens_TokenHash" ON charity."QRCodeTokens" USING btree ("TokenHash");


--
-- TOC entry 4936 (class 1259 OID 25094)
-- Name: IX_RequestDocuments_RequestId; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE INDEX "IX_RequestDocuments_RequestId" ON charity."RequestDocuments" USING btree ("RequestId");


--
-- TOC entry 4889 (class 1259 OID 25095)
-- Name: IX_Specialties_NameAr; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Specialties_NameAr" ON charity."Specialties" USING btree ("NameAr");


--
-- TOC entry 4884 (class 1259 OID 25071)
-- Name: RoleNameIndex; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON charity."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 4895 (class 1259 OID 25097)
-- Name: UserNameIndex; Type: INDEX; Schema: charity; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON charity."Users" USING btree ("NormalizedUserName");


--
-- TOC entry 4944 (class 2606 OID 24823)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES charity."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4945 (class 2606 OID 24838)
-- Name: AspNetUserClaims FK_AspNetUserClaims_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4946 (class 2606 OID 24853)
-- Name: AspNetUserLogins FK_AspNetUserLogins_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4947 (class 2606 OID 24867)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES charity."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4948 (class 2606 OID 24872)
-- Name: AspNetUserRoles FK_AspNetUserRoles_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4949 (class 2606 OID 24887)
-- Name: AspNetUserTokens FK_AspNetUserTokens_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4950 (class 2606 OID 24906)
-- Name: Beneficiaries FK_Beneficiaries_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Beneficiaries"
    ADD CONSTRAINT "FK_Beneficiaries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4959 (class 2606 OID 25055)
-- Name: Consultations FK_Consultations_Doctors_DoctorId1; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Consultations"
    ADD CONSTRAINT "FK_Consultations_Doctors_DoctorId1" FOREIGN KEY ("DoctorId1") REFERENCES charity."Doctors"("Id") ON DELETE CASCADE;


--
-- TOC entry 4960 (class 2606 OID 25060)
-- Name: Consultations FK_Consultations_MedicalRequests_RequestId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Consultations"
    ADD CONSTRAINT "FK_Consultations_MedicalRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES charity."MedicalRequests"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4961 (class 2606 OID 25065)
-- Name: Consultations FK_Consultations_QRCodeTokens_QRCodeTokenId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Consultations"
    ADD CONSTRAINT "FK_Consultations_QRCodeTokens_QRCodeTokenId" FOREIGN KEY ("QRCodeTokenId") REFERENCES charity."QRCodeTokens"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4951 (class 2606 OID 24926)
-- Name: Doctors FK_Doctors_Specialties_SpecialtyId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Doctors"
    ADD CONSTRAINT "FK_Doctors_Specialties_SpecialtyId" FOREIGN KEY ("SpecialtyId") REFERENCES charity."Specialties"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4952 (class 2606 OID 24931)
-- Name: Doctors FK_Doctors_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."Doctors"
    ADD CONSTRAINT "FK_Doctors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4953 (class 2606 OID 24948)
-- Name: LoginHistories FK_LoginHistories_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."LoginHistories"
    ADD CONSTRAINT "FK_LoginHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4955 (class 2606 OID 24989)
-- Name: MedicalRequests FK_MedicalRequests_Beneficiaries_BeneficiaryId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."MedicalRequests"
    ADD CONSTRAINT "FK_MedicalRequests_Beneficiaries_BeneficiaryId" FOREIGN KEY ("BeneficiaryId") REFERENCES charity."Beneficiaries"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4956 (class 2606 OID 24994)
-- Name: MedicalRequests FK_MedicalRequests_Specialties_SpecialtyId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."MedicalRequests"
    ADD CONSTRAINT "FK_MedicalRequests_Specialties_SpecialtyId" FOREIGN KEY ("SpecialtyId") REFERENCES charity."Specialties"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4954 (class 2606 OID 24970)
-- Name: OtpRecords FK_OtpRecords_Users_UserId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."OtpRecords"
    ADD CONSTRAINT "FK_OtpRecords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES charity."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4957 (class 2606 OID 25013)
-- Name: QRCodeTokens FK_QRCodeTokens_MedicalRequests_RequestId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."QRCodeTokens"
    ADD CONSTRAINT "FK_QRCodeTokens_MedicalRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES charity."MedicalRequests"("Id") ON DELETE CASCADE;


--
-- TOC entry 4958 (class 2606 OID 25033)
-- Name: RequestDocuments FK_RequestDocuments_MedicalRequests_RequestId; Type: FK CONSTRAINT; Schema: charity; Owner: postgres
--

ALTER TABLE ONLY charity."RequestDocuments"
    ADD CONSTRAINT "FK_RequestDocuments_MedicalRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES charity."MedicalRequests"("Id") ON DELETE CASCADE;


-- Completed on 2026-06-28 18:11:51

--
-- PostgreSQL database dump complete
--

\unrestrict GvZjcuux9dxt7n4uc9x1c1CSndxDb3dixbp84gOzF82NAgSnJrf6eRhEv3f3cfk

